services:
  ###> doctrine/doctrine-bundle ###
  # Definimos el servicio de la base de datos (MySQL 8.0)
  database:
    # Usamos la imagen oficial de MySQL 8.0
    image: mysql:8.0

    # Compatibilidad para autenticación de contraseñas con Symfony y clientes antiguos
    command: --default-authentication-plugin=mysql_native_password

    # Configuramos las credenciales según tu .env
    environment:
      MYSQL_DATABASE: gamerate_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root_password

    # El healthcheck adaptado para asegurar que MySQL está listo antes que nada
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "admin", "-padmin"]
      timeout: 5s
      retries: 5
      start_period: 30s

    # Mapeo al puerto 3307 para evitar el conflicto con tu proceso local 1301
    ports:
      - "3307:3306"

    # Persistencia de datos + Carga automática de tu data.sql
    volumes:
      - database_data:/var/lib/mysql:rw
      - ./docker/mysql/init:/docker-entrypoint-initdb.d:ro

###< doctrine/doctrine-bundle ###

volumes:
  # Definición del volumen persistente para que no pierdas tus juegos al apagar
  database_data:
