<?php

namespace Container3qDncSY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__PpKZeaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..ppKZea' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'videojuego' => ['privates', '.errored..service_locator..ppKZea.App\\Entity\\Videojuego', NULL, 'Cannot autowire service ".service_locator..ppKZea": it needs an instance of "App\\Entity\\Videojuego" but this type has been excluded because it\'s a Doctrine entity.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'videojuego' => 'App\\Entity\\Videojuego',
            'em' => '?',
        ]);

        if (isset($container->privates['.service_locator..ppKZea'])) {
            return $container->privates['.service_locator..ppKZea'];
        }

        return $container->privates['.service_locator..ppKZea'] = $instance;
    }
}
