<?php

namespace Container3qDncSY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6PbiLw1.App\Controller\AdminController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6PbiLw1.App\\Controller\\AdminController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'vRepo' => ['privates', 'App\\Repository\\VideojuegoRepository', 'getVideojuegoRepositoryService', true],
            'uRepo' => ['privates', 'App\\Repository\\UsuarioRepository', 'getUsuarioRepositoryService', true],
        ], [
            'vRepo' => 'App\\Repository\\VideojuegoRepository',
            'uRepo' => 'App\\Repository\\UsuarioRepository',
        ]))->withContext('App\\Controller\\AdminController::index()', $container);
    }
}
