<?php

namespace Container3qDncSY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVideojuegoControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\VideojuegoController' shared autowired service.
     *
     * @return \App\Controller\VideojuegoController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/VideojuegoController.php';

        $container->services['App\\Controller\\VideojuegoController'] = $instance = new \App\Controller\VideojuegoController();

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\VideojuegoController', $container));

        return $instance;
    }
}
