<?php

namespace Container3qDncSY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVideojuegoControlleraddToWishlistService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..ppKZea.App\Controller\VideojuegoController::addToWishlist()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator..ppKZea'] ?? $container->load('get_ServiceLocator__PpKZeaService'));

        if (isset($container->privates['.service_locator..ppKZea.App\\Controller\\VideojuegoController::addToWishlist()'])) {
            return $container->privates['.service_locator..ppKZea.App\\Controller\\VideojuegoController::addToWishlist()'];
        }

        $instance = $a->withContext('App\\Controller\\VideojuegoController::addToWishlist()', $container);

        if (isset($container->privates['.service_locator..ppKZea.App\\Controller\\VideojuegoController::addToWishlist()'])) {
            return $container->privates['.service_locator..ppKZea.App\\Controller\\VideojuegoController::addToWishlist()'];
        }

        return $container->privates['.service_locator..ppKZea.App\\Controller\\VideojuegoController::addToWishlist()'] = $instance;
    }
}
