<?php

namespace Container3qDncSY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVideojuegoControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4IdwerS.App\Controller\VideojuegoController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4IdwerS.App\\Controller\\VideojuegoController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\VideojuegoRepository', 'getVideojuegoRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\VideojuegoRepository',
        ]))->withContext('App\\Controller\\VideojuegoController::index()', $container);
    }
}
