<?php

namespace Container3qDncSY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVideojuegoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator..ppKZea.App\Entity\Videojuego' shared service.
     *
     * @return \App\Entity\Videojuego
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator..ppKZea": it needs an instance of "App\\Entity\\Videojuego" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
