<?php

namespace ContainerYF9LIRa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EdRb55lService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.edRb55l' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\AdminController::index' => ['privates', '.service_locator.6PbiLw1.App\\Controller\\AdminController::index()', 'getAdminControllerindexService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.3FWkHlB.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.0MQaTBY.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\VideojuegoController::index' => ['privates', '.service_locator.4IdwerS.App\\Controller\\VideojuegoController::index()', 'getVideojuegoControllerindexService', true],
            'App\\Controller\\VideojuegoController::new' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\VideojuegoController::new()', 'getVideojuegoControllernewService', true],
            'App\\Controller\\VideojuegoController::myWishlist' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\VideojuegoController::myWishlist()', 'getVideojuegoControllermyWishlistService', true],
            'App\\Controller\\VideojuegoController::show' => ['privates', '.service_locator..ppKZea.App\\Controller\\VideojuegoController::show()', 'getVideojuegoControllershowService', true],
            'App\\Controller\\VideojuegoController::addToWishlist' => ['privates', '.service_locator..ppKZea.App\\Controller\\VideojuegoController::addToWishlist()', 'getVideojuegoControlleraddToWishlistService', true],
            'App\\Controller\\VideojuegoController::edit' => ['privates', '.service_locator..ppKZea.App\\Controller\\VideojuegoController::edit()', 'getVideojuegoControllereditService', true],
            'App\\Controller\\VideojuegoController::delete' => ['privates', '.service_locator..ppKZea.App\\Controller\\VideojuegoController::delete()', 'getVideojuegoControllerdeleteService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\AdminController:index' => ['privates', '.service_locator.6PbiLw1.App\\Controller\\AdminController::index()', 'getAdminControllerindexService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.3FWkHlB.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.0MQaTBY.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\VideojuegoController:index' => ['privates', '.service_locator.4IdwerS.App\\Controller\\VideojuegoController::index()', 'getVideojuegoControllerindexService', true],
            'App\\Controller\\VideojuegoController:new' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\VideojuegoController::new()', 'getVideojuegoControllernewService', true],
            'App\\Controller\\VideojuegoController:myWishlist' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\VideojuegoController::myWishlist()', 'getVideojuegoControllermyWishlistService', true],
            'App\\Controller\\VideojuegoController:show' => ['privates', '.service_locator..ppKZea.App\\Controller\\VideojuegoController::show()', 'getVideojuegoControllershowService', true],
            'App\\Controller\\VideojuegoController:addToWishlist' => ['privates', '.service_locator..ppKZea.App\\Controller\\VideojuegoController::addToWishlist()', 'getVideojuegoControlleraddToWishlistService', true],
            'App\\Controller\\VideojuegoController:edit' => ['privates', '.service_locator..ppKZea.App\\Controller\\VideojuegoController::edit()', 'getVideojuegoControllereditService', true],
            'App\\Controller\\VideojuegoController:delete' => ['privates', '.service_locator..ppKZea.App\\Controller\\VideojuegoController::delete()', 'getVideojuegoControllerdeleteService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\AdminController::index' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\VideojuegoController::index' => '?',
            'App\\Controller\\VideojuegoController::new' => '?',
            'App\\Controller\\VideojuegoController::myWishlist' => '?',
            'App\\Controller\\VideojuegoController::show' => '?',
            'App\\Controller\\VideojuegoController::addToWishlist' => '?',
            'App\\Controller\\VideojuegoController::edit' => '?',
            'App\\Controller\\VideojuegoController::delete' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\AdminController:index' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\VideojuegoController:index' => '?',
            'App\\Controller\\VideojuegoController:new' => '?',
            'App\\Controller\\VideojuegoController:myWishlist' => '?',
            'App\\Controller\\VideojuegoController:show' => '?',
            'App\\Controller\\VideojuegoController:addToWishlist' => '?',
            'App\\Controller\\VideojuegoController:edit' => '?',
            'App\\Controller\\VideojuegoController:delete' => '?',
        ]);

        if (isset($container->privates['.service_locator.edRb55l'])) {
            return $container->privates['.service_locator.edRb55l'];
        }

        return $container->privates['.service_locator.edRb55l'] = $instance;
    }
}
