<?php

namespace ContainerYF9LIRa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVideojuegoControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..ppKZea.App\Controller\VideojuegoController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator..ppKZea'] ?? $container->load('get_ServiceLocator__PpKZeaService'));

        if (isset($container->privates['.service_locator..ppKZea.App\\Controller\\VideojuegoController::edit()'])) {
            return $container->privates['.service_locator..ppKZea.App\\Controller\\VideojuegoController::edit()'];
        }

        $instance = $a->withContext('App\\Controller\\VideojuegoController::edit()', $container);

        if (isset($container->privates['.service_locator..ppKZea.App\\Controller\\VideojuegoController::edit()'])) {
            return $container->privates['.service_locator..ppKZea.App\\Controller\\VideojuegoController::edit()'];
        }

        return $container->privates['.service_locator..ppKZea.App\\Controller\\VideojuegoController::edit()'] = $instance;
    }
}
